name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prepare release
    steps:
      - uses: actions/checkout@v4
      
      - name: Adjust version in manifest.json
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/reveal_cell_cam/manifest.json
          
      - name: Create zip file
        run: |
          cd custom_components/reveal_cell_cam
          zip -r ../../reveal_cell_cam.zip .
          
      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./reveal_cell_cam.zip
          asset_name: reveal_cell_cam.zip
          asset_content_type: application/zip